name: Build and deploy frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./social-media-react
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: ./social-media-react/pnpm-lock.yaml

      - name: Injecting environment variables
        run: echo "REACT_APP_API_URL=${{ secrets.API_URL }}" >> .env

      - name: Install dependencies
        run: pnpm install

      - name: Running tests
        run: pnpm test

      - name: Building project
        run: pnpm build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./dist/ s3://postagram --delete
